### ISSUE TITLE
The 'height' and 'width' property in the annotations files are different between train and val?

### ISSUE THREAD

**Issue by lyrgwlr** [Jeff-sjtu/CrowdPose#12]
I found the dic['images'][...]['width'] and dic['images'][...]['height'] in crowdpose_train.json are reversed...
And the same position in crowdpose_val.json is right.
Would this effect the result?

**Comment by rika1024** [comment]
I also found this question. And the height and width in test.json are reversed, too

**Comment by firestonelib** [comment]
The image's height and width in (crowdpose_train.json or crowdpose_test.json) is revered.
But the crowdpose_val.json is right. @Jeff-sjtu @Canwang-sjtu

**Comment by Canwang-sjtu** [comment]
Thanks, you are right, we will correct it later ~

________________________________
发件人: muzi ***@***.***>
发送时间: 2021年3月15日 13:15
收件人: Jeff-sjtu/CrowdPose ***@***.***>
抄送: 王灿 ***@***.***>; Mention ***@***.***>
主题: Re: [Jeff-sjtu/CrowdPose] The 'height' and 'width' property in the annotations files are different between train and val? (#12)


The image's height and width in (crowdpose_train.json or crowdpose_test.json) is revered.
But the crowdpose_val.json is right. @Jeff-sjtu<https://github.com/Jeff-sjtu> @Canwang-sjtu<https://github.com/Canwang-sjtu>

―

**Comment by Canwang-sjtu** [comment]
done
