### ISSUE TITLE
Your dataset may have a problem on visibility marking.

### ISSUE THREAD

**Issue by ArchNew** [Jeff-sjtu/CrowdPose#13]
It seems your dataset doesn't mark the occlusion faithfully. It is apparent that your dataset's format is arranged according to the COCO dataset. According to COCO, every keypoint is marked by three numbers: x-axis, y-axis, and visibility. If the keypoint is visible, the third number is 2, if it is occluded, the number is 1, and 0 for unmarked keypoint.

But in your dataset, the visibility marks seem to be arranged randomly. There are instances with all visible keypoints marked as 1 (occluded). I'm wondering how do you set up your dataset's marking on visibility?

**Comment by TianshengSun** [comment]
Hi, I think I meet same problem. It feels like that '0' means invisible keypoints , and '1' and ' 2' means visible keypoints. Can you tell me how did you deal with that?

**Comment by ArchNew** [comment]
> Hi, I think I meet same problem. It feels like that '0' means invisible keypoints , and '1' and ' 2' means visible keypoints. Can you tell me how did you deal with that?

My solution is to ignore the visibility markings.

**Comment by AgntBrwr** [comment]
> > Hi, I think I meet same problem. It feels like that '0' means invisible keypoints , and '1' and ' 2' means visible keypoints. Can you tell me how did you deal with that?
> 
> My solution is to ignore the visibility markings.

It seems to be the case that every time the head and neck are labelled, they are labelled as invisible. I agree with your solution.
