### ISSUE TITLE
Your annotation on 'num_keypoints' doesn't match the actually marked points. 

### ISSUE THREAD

**Issue by ArchNew** [Jeff-sjtu/CrowdPose#16]
It seems the 'num_keypoints' is always less than the actual marked points. I'm wondering do you have some pre-processing methods that aren't mentioned in the Paper. 
BTW, your dataset's quality could use some optimization. Too much 'head' marks are misplaced, and too much bbox and keypoints don't match up. And even have an image (105273.jpg) may come from places like pornhub. I didn't go through all 20 thousand images, so I don't know if it is the only one.

**Comment by Canwang-sjtu** [comment]
this information ‘num_keypoints’ is not important

**Comment by hellojialee** [comment]
Hi, has the CrowPose annotation fixed?
