### ISSUE TITLE
Does the third dimension of the Keypoint Annotations carry any meaning?

### ISSUE THREAD

**Issue by tobiaskalb** [Jeff-sjtu/CrowdPose#2]
In the annotations of the COCO Keypoint  dataset the third dimension of the keypoints is a visibility flag v defined as v=0: not labeled (in which case x=y=0), v=1: labeled but not visible, and v=2: labeled and visible. 

What is the definition of the third dimension of the keypoints in CrowdPose?

**Comment by jeffffffli** [comment]
It is a label flag. When v=0, it means the keypoint is not labeled.
