### ISSUE TITLE
problem about eval metircs

### ISSUE THREAD

**Issue by ericzw** [Jeff-sjtu/CrowdPose#3]
Hi, thanks for your work!

I have a problem about your evaluation metrics. 
![image](https://user-images.githubusercontent.com/34059431/58764353-8be3dc00-8598-11e9-9660-a34ecba24127.png)
![image](https://user-images.githubusercontent.com/34059431/58764389-e5e4a180-8598-11e9-966d-fe74718e2064.png)

Are these AR(easy, medium , hard)(figure1) the AP(easy, medium , hard)(Figure2) shown in your paper?

**Comment by Canwang-sjtu** [comment]
Hi, this is a bug and I will fix it.
